#pragma once
/**
 * \file path.hpp
 * Paths for pure pursuit: cubic Bezier segments sampled into a dense list of
 * points with curvature-aware speeds.
 *
 * You normally do NOT build these by hand — the AKLib Planner (planner/
 * aklib-planner.html) draws them visually and generates this code for you:
 *
 *   // Generated by AKLib Planner
 *   aklib::Path rush = aklib::Path::bezier({
 *       {12, 36}, {24, 36}, {36, 58}, {48, 58},   // segment 1 (P0 C0 C1 P1)
 *       {60, 58}, {70, 40}, {70, 24},             // segment 2 (C0 C1 P1) ...
 *   });
 *   chassis.follow(rush, {.lookahead = 12});
 *
 * Requirements: odometry (any combo from odometry.hpp).
 */

#include <vector>

#include "aklib/pose.hpp"

namespace aklib {

/** Options for Path::bezier(). Defaults are sensible; override with
 *  designated initializers: Path::bezier(pts, {.spacing = 0.5}). */
struct PathOptions {
    /** Distance between sampled points, inches. Smaller = smoother, bigger
     *  memory. 0.5 in is plenty for VEX. */
    double spacing = 0.5;
    /** Overall speed cap for the path, fraction of full speed (0..1]. */
    double maxSpeed = 1.0;
    /** How hard to slow for curves. speed = min(maxSpeed, turnK / |curvature|).
     *  Smaller = slower cornering. Typical range 0.5 - 2.0. */
    double turnK = 1.0;
    /** Deceleration limit for the backward smoothing pass, in "fraction of
     *  full speed per inch". Prevents asking the robot to brake instantly
     *  into slow corners. */
    double decel = 0.06;
    /** Speed at the very end of the path (0 = come to rest; set > 0 when
     *  chaining into another motion). */
    double endSpeed = 0.0;
};

class Path {
public:
    struct PathPoint {
        Point p;          ///< field position, inches
        double speed;     ///< planned speed, fraction of full output (0..1]
        double distance;  ///< arc length from path start to here, inches
    };

    Path() = default;

    /**
     * Build a path from chained cubic Bezier segments.
     * Control point layout: 4 points for the first segment
     * (P0, C0, C1, P1), then 3 more per additional segment (C0, C1, P1) —
     * each new segment starts where the previous ended.
     */
    static Path bezier(const std::vector<Point>& controls,
                       const PathOptions& options = {});

    /** Straight line from a to b (handy for programmatic paths). */
    static Path line(Point a, Point b, const PathOptions& options = {});

    const std::vector<PathPoint>& points() const { return pts_; }
    bool empty() const { return pts_.empty(); }
    double length() const { return pts_.empty() ? 0 : pts_.back().distance; }
    const PathPoint& back() const { return pts_.back(); }

    /** Index of the path point closest to `p`, searching from fromIndex
     *  onward (monotonic — pure pursuit never looks backward). */
    std::size_t closestIndex(const Point& p, std::size_t fromIndex = 0) const;

    /**
     * The pure-pursuit lookahead point: first path location at exactly
     * `lookahead` inches from `robot`, at or after startIndex. Falls back to
     * the closest point if the circle doesn't intersect (robot far off path),
     * and to the final point when near the end.
     * \param[in,out] startIndex  advanced as the robot progresses; pass the
     *                            same variable every loop.
     */
    Point lookaheadPoint(const Point& robot, double lookahead,
                         std::size_t& startIndex) const;

private:
    void finalize_(const PathOptions& options);  ///< distances + speed passes
    std::vector<PathPoint> pts_;
};

} // namespace aklib
